version: '3'

services:
  nodejs:
    image: eslamanwar/name-contests:0.1.120
    container_name: nodejs
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3000 
      MONGO_DB: contests
      MONGO_PORT: 27017
      MONGO_HOSTNAME: mongodb
      DATABASE_URL: postgres://user:pass@postgres:5432/contests
            
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    links:
      - mongodb
      - postgres        
    depends_on:
      - mongodb       
      - postgres        
    networks:
      - app-network


  mongodb:
    image: mongo:4
    container_name: mongodb
    restart: unless-stopped
    env_file: .env
    volumes:     
      - mongodbdata:/data/db
    networks:
      - app-network  

  postgres:
    image: postgres:10.4
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: contests
    volumes:
      - postgresdata:/var/lib/postgresql/data     
    networks:
      - app-network        
      
networks:
  app-network:
    driver: bridge

volumes:
  mongodbdata:
  node_modules:
  postgresdata:        
