version: 2
jobs:
  # CLI publishing
  cli_publish:
    docker:
      - image: circleci/node:10.16.3
        environment:      
          PGHOST: 127.0.0.1
      - image: circleci/mongo:4
        environment:
          MONGO_INITDB_DATABASE: contests      
      - image: circleci/postgres:10.3-alpine
        environment:
          POSTGRES_DB: contests
          POSTGRES_USER: root
          TEST_DATABASE_URL: postgresql://root@localhost/contests
    working_directory: ~/repo           
    steps:
      - checkout
      - run: sudo apt install -y postgresql-client || true
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run:
          name: Waiting for PostgreSQL to start
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 2
            done
            echo Failed waiting for Postgres && exit 1
      - run:
          name: Wait for Mongo to start
          # preinstalled in circleci/* docker image
          command: dockerize -wait tcp://127.0.0.1:27017 -timeout 120s
      - run:
          name: install dependencies
          command: yarn install --no-cache --frozen-lockfile   
      - run:
          name: load data into database
          command: node database/loadTestMongoData.js && node database/mdb.js  && node database/pgdb.js  
      - run: 
          yarn test
workflows:
  version: 2
  build:
    jobs:
      - cli_publish:
          filters:
            tags:
              only: /.*/
            branches:
              only:
                - master
                - beta
                - alpha          
